name: PR

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
      branches:
      - main

jobs:
  build-with-xk6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Build with xk6
        run: |
          go install go.k6.io/xk6/cmd/xk6@latest
          xk6 build --with $(go list -m)=.

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Run unit tests
        run: go test -v -cover -race ./...
