name: publish 

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: grafana/xk6-disruptor-agent

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get image version
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
             IMAGE_VERSION=$GITHUB_REF_NAME
          else
             IMAGE_VERSION="latest"
          fi
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
      - name: Build
        run: |
          CGO_ENABLED=0 
          go build -o images/agent/build/xk6-disruptor-agent ./cmd/agent
          docker build -t $IMAGE_NAME images/agent
      - name: Log into ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish latest agent image to ghcr.io
        env:
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}
        run: |
          IMAGE_TAG="$REGISTRY/$IMAGE_NAME:$IMAGE_VERSION"
          docker tag $IMAGE_NAME $IMAGE_TAG
          docker push $IMAGE_TAG
